# Generated by Django 5.0.4 on 2024-05-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(height_field=100, upload_to='media/skilllogos/', width_field=100)),
                ('skill1', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=20)),
                ('Description', models.TextField(max_length=2000)),
                ('Tools', models.ManyToManyField(to='APP.skillsmodel')),
            ],
        ),
    ]
