# Generated by Django 5.0.4 on 2024-05-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_alter_skillsmodel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(default='https://example.com', null=True),
        ),
    ]
